Feature/exercício 01
FLindenmeyer/Orion-Bootcamp pull request #1
Opened 2023-10-09 15:29 UTC by FLindenmeyer

Adicionado o nodemodules e alguns arquivos de configuração no primeiro commit. Seguido da resolução do exercício 1A e 1B.

2023-10-09 16:14 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Fabrício Linden.] Exercício 1](https://trello.com/c/r2U6SvFc/67-fabr%C3%ADcio-linden-exerc%C3%ADcio-1)

2023-10-10 21:02 UTC, aLiviaMs requested changes
Código está bom no geral!! 
Apenas sugeri algumas melhorias a serem feitas.

2023-10-10 21:02 UTC, aLiviaMs commented on Exercícios/1 - Exercício/indexA.ts
> +function findVowelsQuantity(text: string) {
Faltou a tipagem do retorno da função.

2023-10-10 21:02 UTC, aLiviaMs commented on Exercícios/1 - Exercício/indexA.ts
> +  const Vowels: string[] = ["a", "e", "i", "o", "u"];
Casos em que vogais acentuadas apareçam não serão contabilizadas na contagem, pela falta dos mesmos no array.
Exemplo: vovó seria contabilizado como apenas 1 vogal, quando, na verdade, existem duas.

Recomendo a utilização de regex + .match() para comportar esses casos sem que o array fique muito grande de letras repetidas.

`vowelsRegex = /[aeiouáàâãéêíóôõúü]/i`

Documentação sobre [Expressões Regulares](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_expressions) e seus tipos de uso. (As possibilidades com ele são infinitas, é bem útil)

2023-10-10 21:02 UTC, aLiviaMs commented on Exercícios/1 - Exercício/indexB.ts
> +const handleSubmit = (ev: SubmitEvent) => {
mesma coisa, Faltou a tipagem do retorno da função.

2023-10-10 21:02 UTC, aLiviaMs commented on Exercícios/1 - Exercício/indexB.ts
> +    const result = vowelsQuantity.length;
faltou tipar o result

2023-10-10 21:02 UTC, aLiviaMs commented on Exercícios/1 - Exercício/indexB.ts
> +  const h4 = document.getElementById("result");
faltou tipar a const h4

2023-10-11 02:47 UTC, robsonfgomes commented
Recomendo não utilizar acentos ou caracteres especiais ao definir os nomes das branchs. O git pode não identificar as branchs, principalmente se estiver usando linha de comando.
Padrão ideal: feature/exercicio-1, feature/exercicio-2, etc.

2023-10-11 13:04 UTC, aLiviaMs approved these changes

2023-10-11 13:06 UTC, merged