Feature/exercício 02
FLindenmeyer/Orion-Bootcamp pull request #2
Opened 2023-10-09 18:30 UTC by FLindenmeyer

Solicito a revisão do Exercício 2. 
Foi dividido em 2 partes, das alternativas A até a D no primeiro commit e a E no segundo commit.

2023-10-09 18:32 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Fabrício Linden.] Exercício 2](https://trello.com/c/1Y8W0oSJ/68-fabr%C3%ADcio-linden-exerc%C3%ADcio-2)

2023-10-11 21:36 UTC, aLiviaMs requested changes

2023-10-11 21:36 UTC, aLiviaMs commented on Exercícios/2 - Exercício/imperative.ts
> +function removeItemByIdImperativo(id: number): void {
Mantenha todo o código em apenas uma linguagem, misturar inglês e português ao mesmo tempo não é uma boa prática. 

Comentários e retornos não precisam estar em inglês, ex: ``` console.log(`\nC) Item com id=${id} removido da lista! `);```

2023-10-11 21:36 UTC, aLiviaMs commented on Exercícios/2 - Exercício/imperative.ts
> +  const name = person ? person.name : "Nome não encontrado.";
Não esqueça de tipar todas as variaveis.

2023-10-13 14:49 UTC, aLiviaMs approved these changes

2023-10-13 14:49 UTC, merged